-- Orders table for final project
-- Simple and functional purchase system

CREATE TABLE IF NOT EXISTS public.orders (
    order_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL,
    inv_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delivery_address TEXT NOT NULL,
    order_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    order_total NUMERIC(10,2) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_account FOREIGN KEY (account_id) REFERENCES account (account_id),
    CONSTRAINT fk_orders_inventory FOREIGN KEY (inv_id) REFERENCES inventory (inv_id)
);

-- Sample data for testing
INSERT INTO public.orders (account_id, inv_id, delivery_address, order_total) 
VALUES (5, 20, '123 Main St, Anytown, State 12345', 25000.00);

-- INSERT INTO public.orders (account_id, inv_id, delivery_address, order_total) 
-- VALUES (1, 1, '123 Main St, Anytown, State 12345', 25000.00);